In [1]:
import tensorflow as tf
import numpy as np
import pandas as pd
import pickle

/Users/utkarshjaiswal/Desktop/Machine_Learning/venv/lib/python3.9/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(

In [ ]:
from tensorflow.keras.models import load_model

In [4]:
#Load the trained model,scaler pickle,ohe

model=load_model('model.h5')

with open('label_encoder_gender.pkl','rb') as file:
    label_encoder_gender=pickle.load(file)

with open('ohe_geography.pkl','rb') as file:
    ohe_geography=pickle.load(file)

with open('scaler.pkl','rb') as file:
    scaler=pickle.load(file)

WARNING:absl:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

In [26]:
# Example input data

input_data = {
    'CreditScore': 600,
    'Geography': 'France',
    'Gender': 'Male',
    'Age': 40,
    'Tenure': 3,
    'Balance': 60000,
    'NumOfProducts': 2,
    'HasCrCard': 1,
    'IsActiveMember': 1,
    'EstimatedSalary': 50000
}

In [27]:
geo_encoded=ohe_geography.transform([[input_data['Geography']]]).toarray()
geo_encoded_df=pd.DataFrame(geo_encoded,columns=ohe_geography.get_feature_names_out(['Geography']))

/Users/utkarshjaiswal/Desktop/Machine_Learning/venv/lib/python3.9/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(

In [28]:
geo_encoded_df

   Geography_France  Geography_Germany  Geography_Spain
0               1.0                0.0              0.0

In [29]:
input_df=pd.DataFrame([input_data])
input_df

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
0,600,France,Male,40,3,60000,2,1,1,50000

In [30]:
#Encode categorical inputs

input_df['Gender']=label_encoder_gender.transform(input_df['Gender'])

In [37]:
input_df

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
0,600,France,1,40,3,60000,2,1,1,50000

In [40]:
#Combine one hot encoded data to my input data
input_df=pd.concat([input_df.drop('Geography',axis=1),geo_encoded_df],axis=1)

In [45]:
input_df

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Geography_France,Geography_Germany,Geography_Spain
0,600,1,40,3,60000,2,1,1,50000,1.0,0.0,0.0

In [46]:
#Scaling the input data

input_scaled=scaler.transform(input_df)

In [48]:
#predict whether the person will exit or not

prediction=model.predict(input_scaled)
prediction

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step

array([[0.0003956]], dtype=float32)

In [49]:
prediction_probability=prediction[0][0]
prediction_probability

np.float32(0.0003955978)

In [50]:
if prediction_probability>0.5:
    print('The person is likely to churn or leave')
else:
    print('The person is not likely to leave or churn')

The person is not likely to leave or churn